# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            mongodb-version: ['3.6.14', '4.0.10', '4.2.8', '4.4.3']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Add dockerhost to OS host file
      run: sudo echo "127.0.0.1 dockerhost" >> | sudo tee -a /etc/hosts
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle agains host ${{ matrix.mongodb-version }}
      run: ./gradlew clean build --no-daemon -DmongoReplicaSetProperties.mongoDockerImageName=mongo:${{ matrix.mongodb-version }}
    - name: Build with Gradle in docker-only mode ${{ matrix.mongodb-version }}
      env:
          MONGO_VERSION: ${{ matrix.mongodb-version }}
      run: |
        docker-compose -f docker-compose-it-test.yml up -d;
        docker wait run-it-test-mongodb-replica-set;
        docker logs run-it-test-mongodb-replica-set;
        if [[ $(docker inspect run-it-test-mongodb-replica-set --format='{{.State.ExitCode}}') == '1' ]]; then
        echo $(docker inspect run-it-test-mongodb-replica-set --format='{{json .State}}');
        exit 1;
        fi
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      if: ${{ success() }}
    - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
      run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
